---
openshift_version: 4.5
openshift_fcos_version: 32.20200824.3.0

openshift_cluster_name: ocp4
openshift_install_root: "{{ ansible_user_dir }}/openshift"
openshift_install_dir: "{{ openshift_install_root }}/{{ openshift_fqdn }}"
openshift_terraform_dir: "{{ openshift_install_dir }}/terraform"
openshift_images_dir: "{{ openshift_install_root }}/images"
openshift_terraform_files: terraform

openshift_packages:
  - python3-openshift

openshift_download_osimages: true
openshift_url_filename_regex: '(.*\.qcow2)(?:\.\w+)?$'
openshift_rhcos_url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ openshift_version }}/latest/rhcos-qemu.x86_64.qcow2.gz
openshift_fcos_url: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/{{ openshift_fcos_version }}/x86_64/fedora-coreos-{{ openshift_fcos_version }}-qemu.x86_64.qcow2.xz
openshift_rhcos_image_filename: "{{ openshift_rhcos_url | basename | regex_replace(openshift_url_filename_regex, '\\1') }}"
openshift_rhcos_image: "{{ openshift_images_dir }}/{{ openshift_rhcos_image_filename }}"
openshift_fcos_image_filename: "{{ openshift_fcos_url | basename | regex_replace(openshift_url_filename_regex, '\\1') }}"
openshift_fcos_image: "{{ openshift_images_dir }}/{{ openshift_fcos_image_filename }}"

openshift_master_osimage: "{{ openshift_images_dir }}/master.{{ openshift_rhcos_image_filename }}"
openshift_worker_osimage: "{{ openshift_images_dir }}/worker.{{ openshift_rhcos_image_filename }}"
openshift_bootstrap_osimage: "{{ openshift_master_osimage }}"
openshift_loadbalancer_osimage: "{{ openshift_images_dir }}/loadbalancer.{{ openshift_fcos_image_filename }}"

openshift_master_storage_size: 120G
openshift_worker_storage_size: 120G
openshift_bootstrap_storage_size: 120G
openshift_loadbalancer_storage_size: 40G

openshift_worker_vcpus: 2
openshift_worker_memory: 8192

openshift_api_cname: "{{ openshift_hosts.loadbalancers[0].names | first }}.{{ openshift_fqdn }}"
openshift_api_internal_cname: "{{ openshift_api_cname }}"
openshift_apps_cname: "{{ openshift_api_cname }}"

openshift_libvirt_storage_pool: default
openshift_network_name: openshift
openshift_network_template: openshift-network.xml.j2
openshift_network_bridge_name: "{{ openshift_network_name }}-br"
openshift_network_forward_mode: nat
openshift_network_cidr: 192.168.200.0/24
openshift_network_ip: "{{ openshift_network_cidr | ipaddr('net') | ipaddr(1) | default(openshift_network_cidr | ipaddr('ip/prefix') | ipaddr('ip')) }}"
openshift_network_dhcp_start: "{{ openshift_network_ip | ipaddr('next_usable') }}"
openshift_network_dhcp_end: "{{ openshift_network_ip | ipaddr('last_usable') }}"
openshift_network_mac_prefix: '52:54:00'

openshift_install_config_template: install-config.yml.j2
openshift_loadbalancer_ign_template: loadbalancer.ign.j2
openshift_loadbalancer_systemd_template: loadbalancer-systemd.conf.j2
openshift_loadbalancer_image: docker.io/haproxytech/haproxy-alpine:2.1
openshift_loadbalancer_volume: "{{ openshift_haproxy_config_path | dirname }}:/usr/local/etc/haproxy:ro"
openshift_haproxy_template: haproxy.cfg.j2
openshift_haproxy_balance_mode: source
openshift_haproxy_config_path: /etc/haproxy/haproxy.cfg



# to do: make names defined by default
openshift_hosts:
  loadbalancers:
    - names: [lb]
      ip: "{{ openshift_network_dhcp_start | ipmath(1) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('lb.' + openshift_fqdn) }}"
  bootstraps:
    - names: [bootstrap]
      ip: "{{ openshift_network_dhcp_start | ipmath(2) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('bootstrap.' + openshift_fqdn) }}"
  masters:
    - names:
        - master-0
        - etcd-0
      ip: "{{ openshift_network_dhcp_start | ipmath(3) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('master-0.' + openshift_fqdn) }}"
    - names:
        - master-1
        - etcd-1
      ip: "{{ openshift_network_dhcp_start | ipmath(4) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('master-1.' + openshift_fqdn) }}"
    - names:
        - master-2
        - etcd-2
      ip: "{{ openshift_network_dhcp_start | ipmath(5) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('master-2.' + openshift_fqdn) }}"
  workers:
    - names: [worker-0]
      ip: "{{ openshift_network_dhcp_start | ipmath(6) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('worker-0.' + openshift_fqdn) }}"
    - names: [worker-1]
      ip: "{{ openshift_network_dhcp_start | ipmath(7) }}"
      mac: "{{ openshift_network_mac_prefix | random_mac('worker-1.' + openshift_fqdn) }}"
