- name: Check if {{ client }} exists
  when: not(oc_force_install | bool)
  stat:
    path: "{{ dest }}"
  register: dest_file

- when: oc_force_install or not(dest_file.stat.exists)
  block:
  - name: Download & install {{ client }} (archived)
    when: src is search(oc_archive_regex)
    unarchive:
      remote_src: yes
      src: "{{ src }}"
      dest: "{{ oc_install_dir }}"
      owner: "{{ oc_owner }}"
      group: "{{ oc_group }}"
      mode: "{{ oc_mode }}"
    become: "{{ oc_become }}"

  - name: Download & install {{ client }} (binary)
    when: not(src is search(oc_archive_regex))
    get_url:
      url: "{{ src }}"
      dest: "{{ dest }}"
      owner: "{{ oc_owner }}"
      group: "{{ oc_group }}"
      mode: "{{ oc_mode }}"
    become: "{{ oc_become }}"
