---
- name: Create installation directory
  file:
    path: "{{ oc_install_dir }}"
    state: directory
    owner: "{{ oc_owner }}"
    group: "{{ oc_group }}"
  become: "{{ oc_become }}"

- name: Download & install openshift clients
  include_tasks: install-client.yml
  vars:
    src: "{{ openshift_client_urls[client] }}"
    dest: "{{ oc_install_dir }}/{{ client }}"
  loop: "{{ openshift_clients }}"
  loop_control:
    loop_var: client
