---
- name: Copy terraform files
  copy:
    src: "{{ openshift_terraform_files }}"
    dest: "{{ openshift_terraform_dir }}"

- name: Provision VMs
  terraform:
    project_path: "{{ openshift_terraform_dir }}"
    state: present
    force_init: yes
    variables:
      fqdn: "{{ openshift_fqdn }}"
      network_name: "{{ openshift_network_name }}"
      storage_pool: "{{ openshift_libvirt_storage_pool }}"
      master_image: "{{ openshift_master_osimage }}"
      master_names: "{{ openshift_hosts.masters | map(attribute='names') | map('first') | list | to_json }}"
      master_macs: "{{ openshift_hosts.masters | map(attribute='mac') | list | to_json }}"
      worker_image: "{{ openshift_worker_osimage }}"
      worker_names: "{{ openshift_hosts.workers | map(attribute='names') | map('first') | list | to_json }}"
      worker_macs: "{{ openshift_hosts.workers | map(attribute='mac') | list | to_json }}"
      worker_vcpu: "{{ openshift_worker_vcpus }}"
      bootstrap_image: "{{ openshift_bootstrap_osimage }}"
      bootstrap_names: "{{ openshift_hosts.bootstraps | map(attribute='names') | map('first') | list | to_json }}"
      bootstrap_macs: "{{ openshift_hosts.bootstraps | map(attribute='mac') | list | to_json }}"
      loadbalancer_image: "{{ openshift_loadbalancer_osimage }}"
      loadbalancer_names: "{{ openshift_hosts.loadbalancers | map(attribute='names') | map('first') | list | to_json }}"
      loadbalancer_macs: "{{ openshift_hosts.loadbalancers | map(attribute='mac') | list | to_json }}"
