_system: "{{ ansible_system | lower }}"
_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
_sysarch: "{{ _system }}-{{ _arch }}"

_archive_regex: '.*\.tar\.gz$'
_extra_opts_remove_sysarch:
  - --transform
  - s/-{{ _sysarch }}//

_openshift_client_defaults:
  oc:
    url: "{{ openshift_clients_mirror_url }}/ocp/{{ openshift_clients_ocp_version }}/openshift-client-{{ _system }}.tar.gz"
    include:
      - oc
      - kubectl
  oc-mirror:
    url: "{{ openshift_clients_mirror_url }}/ocp/{{ openshift_clients_ocp_version }}/oc-mirror.tar.gz"
    include:
      - oc-mirror
  openshift-install:
    url: "{{ openshift_clients_mirror_url }}/ocp/{{ openshift_clients_ocp_version }}/openshift-install-{{ _system }}.tar.gz"
    include:
      - openshift-install
  opm:
    url:  "{{ openshift_clients_mirror_url }}/ocp/{{ openshift_clients_ocp_version }}/opm-{{ _system }}.tar.gz"
    include:
      - opm
  butane:
    url: "{{ openshift_clients_mirror_url }}/butane/{{ openshift_clients_butane_version }}/butane-{{ _arch }}"
    filename: butane
  helm:
    url: "{{ openshift_clients_mirror_url }}/helm/{{ openshift_clients_helm_version }}/helm-{{ _sysarch }}.tar.gz"
    include:
      - helm-{{ _sysarch }}
    extra_opts: "{{ _extra_opts_remove_sysarch }}"
  kam:
    url: "{{ openshift_clients_mirror_url }}/kam/{{ openshift_clients_kam_version }}/kam-{{ _sysarch }}.tar.gz"
    include:
      - kam
  odo:
    url: "{{ openshift_clients_mirror_url }}/odo/{{ openshift_clients_odo_version }}/odo-{{ _sysarch }}.tar.gz"
    include:
      - odo
  tkn:
    url: "{{ openshift_clients_mirror_url }}/pipelines/{{ openshift_clients_tkn_version }}/tkn-{{ _sysarch }}.tar.gz"
    include:
      - tkn
      - tkn-pac
      - opc
  kn:
    url: "{{ openshift_clients_mirror_url }}/serverless/{{ openshift_clients_kn_version }}/kn-{{ _sysarch }}.tar.gz"
    include:
      - kn-{{ _sysarch }}
    extra_opts: "{{ _extra_opts_remove_sysarch }}"
